version: '3.8'

services:

  backend:
    build: ./backend
    container_name: nodejs_backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8087:8087"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend/101411424_comp3133_assignment2
      dockerfile: Dockerfile
    container_name: angular_frontend
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ./frontend/101411424_comp3133_assignment2:/app
      - /app/node_modules
    command: ["ng", "serve", "--host", "0.0.0.0"]


